### ISSUE TITLE
Fallback to conf.sample.ts when conf.ts does not exist

### ISSUE THREAD

**Issue by jraviotta** [magic8bot/magic8bot#140]
Since conf.ts is not available in git repo, automated docker builds will fail.

**Comment by Shawn8901** [comment]
Travis has now a pre_install script, which copies the `conf.sample.ts` to `conf.ts` in #161. 
After merging it, TravisCI will use the conf.sample.ts "as fallback". 
would the issue then be solved for you?

**Comment by jraviotta** [comment]
That should solve the problem for Travis builds. This was also aimed at giving the user some defaults the first time they start the app. Since the app preferences will not be stored in conf.ts as they were in zenbot, this is less important for UX. The more important issue now is figuring out how to set the db host automatically. When running locally, it should be `localhost`, in Docker `mongodb`, on a server it depends on whether the app is in a VM or a container.

**Comment by Shawn8901** [comment]
I agree. 
I have added a sed to the Dockerfile to change the value in the conf.sample.ts to a valid value.
https://github.com/magic8bot/magic8bot/pull/178

**Comment by notVitaliy** [comment]
closing in favor of #178
