### ISSUE TITLE
Provide docker-friendly mongo config

### ISSUE THREAD

**Issue by jraviotta** [magic8bot/magic8bot#141]
The mogo container refuses connections in the container. Probably a networking config issue.

**Comment by Shawn8901** [comment]
as written in #137 the bot cant connect to mongodb because of a wrong configuration. the default tries to connect to `localhost`.
you have to change the hostname in conf.ts to `mongodb`, afterwards it connects successfully for the current docker-compose.yml

**Comment by notVitaliy** [comment]
Closing in favor of #178
