### ISSUE TITLE
Implement a configurable accepted slipperage before order adjustment

### ISSUE THREAD

**Issue by Shawn8901** [magic8bot/magic8bot#188]
Currently the OrderEngine should adjust an Order after it recognizes a price change in checkOrder.
So it will cancel the Order and create an Adjustment for this order.
But if the price change from the placed order is marginal, it should keep the order on my opinion.
So it would be a nice idea to accept an slipperage on a decent percentage, because the current price is still  near the placed orders price.

the first default value for the sample.conf.ts could be 0%, so it will keep the current implementation.

**Comment by notVitaliy** [comment]
imo, I think it should adjust orders even if they slip 0.01 USD. This will make sure that the order stays at the top of the orderbook. I'm open to discussion about this.

**Comment by notVitaliy** [comment]
Hmm... actually. I think you're right. Giving the user control over this makes more sense. PR incoming.

**Comment by Shawn8901** [comment]
will be fixed with #191
