### ISSUE TITLE
Decouple configuration from runtime

### ISSUE THREAD

**Issue by notVitaliy** [magic8bot/magic8bot#207]
Remove the need for a `conf.ts` file.

The only configuration that should be needed for the bot to start is a mongodb connection. These connection parameters should be provided via environment variables.

```ruby
MONGO_HOST=localhost
MONGO_PORT=27017
MONGO_DB=magic8bot
MONGO_USER=
MONGO_PASS=
```

All strategy configuration should happen during runtime. This will allow for hotswapping strategies and adjusting wallets from a UI.

**Comment by jraviotta** [comment]
Presently, `index.tx` requires `conf.ts` which is a problem for Docker. Moving mongo credentials to environment variables will solve the problem but Docker builds will fail until this issue is resolved.
