### ISSUE TITLE
Current state

### ISSUE THREAD

**Issue by vertic4l** [magic8bot/magic8bot#244]
Hi there!

@notVitaliy could you give an update what works right now and what need to be done?

**Comment by vertic4l** [comment]
Okay, i've found the ui repo now.

There are some things to do obviously, but it's great as far as i can see.
React, MobX with TypeScript are great choices!

I'll start working on it :)

**Comment by notVitaliy** [comment]
Oh man. It's been so long since I've worked on this. From what I remember, it "works" but the strategy that's there doesn't.

The last thing I was working on was trying to get it to send data back and forth through websockets.  I didn't complete that and it's in a pretty broken state right now.

**Comment by vertic4l** [comment]
@notVitaliy that's sad to hear. i really like the code base and am trying to get into it and figure out how to continue. A simulation seems to be missing which i would like to have to test the strategies.

**Comment by jorisw** [comment]
@notVitaliy What caused you to cease work on this? Have you lost faith in getting this to a state in which it succeeds at what it aims to do?

Did you choose to use a different bot instead?

Would be nice for visitors of this project to understand why it's stale, and whether it's worth trying it out, and/or doing additional work on it.
