### ISSUE TITLE
MongoNetworkError

### ISSUE THREAD

**Issue by XMVZ** [magic8bot/magic8bot#259]
Really would love to use this tool, however running into this error:
https://gyazo.com/aed5c259cac0ba7a566e9a1948b4bdbe

Can someone give me a bit of help to get to the finish line?

Thanks!

**Comment by notVitaliy** [comment]
`Error: connect ECONNREFUSED 127.0.0.1:27012`

Looks like you don't have mongo running. If you do, it's not running on the right port.
