### ISSUE TITLE
Refactor analysis -- ema

### ISSUE THREAD

**Issue by jraviotta** [magic8bot/magic8bot#54]
Remove the dependence on the `s` var. 

- [x] magic8bot/src/analysis/ema.ts

- [ ] magic8bot/src/analysis/ta_ema.ts

**Comment by Shawn8901** [comment]
The basic EMA indicator was already ported in ab5f3d20a5c0faa5c8bc3c544172a432608d0f21

Do you want to support second based on TALib?
If not the issue is completed, otherwise ta_ema is still open
