### ISSUE TITLE
Plan automated testing

### ISSUE THREAD

**Issue by jraviotta** [magic8bot/magic8bot#88]
Project administration #82
Thoughts on automated testing on check in?

**Comment by Shawn8901** [comment]
We should setup a TravisCI for this. The package.json file already includes a test and lint step, which has then to be executed by Travis. Through this we will also have a build version on every or and we could set a successful build as quality gate for merges.

**Comment by Shawn8901** [comment]
@jraviotta as we now have travis building everything and also auto executing the unit tests, we now have enabled automated testing. 
As the open work to do is to write a test for everything, i would suggest that the "administration" project is done. What do you think?
